// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TSquad.BookHub.ShoppingCart.WebApi.Infrastructure.Persistence.Contexts;

#nullable disable

namespace TSquad.BookHub.ShoppingCart.WebApi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContextShoppingCart))]
    partial class ApplicationContextShoppingCartModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TSquad.BookHub.ShoppingCart.WebApi.Domain.Entities.ShoppingCartItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ShoppingCartItemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ShoppingCartSessionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_ShoppingCartItems");

                    b.HasIndex("ShoppingCartSessionId");

                    b.ToTable("ShoppingCartItems", (string)null);
                });

            modelBuilder.Entity("TSquad.BookHub.ShoppingCart.WebApi.Domain.Entities.ShoppingCartSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ShoppingCartSessionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_ShoppingCartSessions");

                    b.ToTable("ShoppingCartSessions", (string)null);
                });

            modelBuilder.Entity("TSquad.BookHub.ShoppingCart.WebApi.Domain.Entities.ShoppingCartItem", b =>
                {
                    b.HasOne("TSquad.BookHub.ShoppingCart.WebApi.Domain.Entities.ShoppingCartSession", "ShoppingCartSession")
                        .WithMany("ShoppingCartItems")
                        .HasForeignKey("ShoppingCartSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ShoppingCartItems_ShoppingCartSessions");

                    b.Navigation("ShoppingCartSession");
                });

            modelBuilder.Entity("TSquad.BookHub.ShoppingCart.WebApi.Domain.Entities.ShoppingCartSession", b =>
                {
                    b.Navigation("ShoppingCartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
